project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: 1
files:
  - source: /manager/app/src/main/res/values/strings.xml
    translation: /manager/app/src/main/res/values-%two_letters_code%/strings.xml
