name: Crowdin Action

on:
  push:
    branches: [ main ]
    paths:
      - 'manager/app/src/main/res/values/strings.xml'
      - 'manager/app/src/main/res/values-*/strings.xml'
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Crowdin Action
      uses: crowdin/github-action@v2
      with:
        upload_sources: true
        upload_translations: true
        auto_approve_imported: true
        download_translations: true
        skip_untranslated_files: false
        skip_untranslated_strings: true

        create_pull_request: true
        localization_branch_name: "Crowdin"
        pull_request_labels: 'enhancement, translation'
        pull_request_title: 'opt: sync translation from Crowdin'

        config: 'crowdin.yml'
        crowdin_branch_name: "main"
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}